#!/bin/bash
# Remove all build artifacts (files and folders generated by build.sh)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "Cleaning build artifacts..."

sudo rm -rf \
    output \
    postgresql-* \
    pglite-wasm \
    pglite-link.sh \
    wasi.done \
    patches-REL_* \
    pglite-REL_* \
    docker/sdk

echo "Clean complete."
