#!/bin/bash
# Remove all build artifacts (files and folders generated by build.sh)
set -e

SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
cd "$SCRIPT_DIR"

echo "Cleaning build artifacts..."

sudo rm -rf \
    output \
    postgresql-src \
    pglite-wasm \
    pglite-link.sh \
    wasi.done \
    docker/sdk \
    *.out \
    postgresql-REL_17_5_WASM-pglite

echo "Clean complete."
